{% set name = "rectangle-packer" %}
{% set version = "2.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1ad5b1edc35e933d1655b2d8e2d345cb2f81a2df135298c8601f74d3dce8d6e9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3                              # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython <3
    - pip
    - python
    - setuptools >=18.0
  run:
    - python

test:
  imports:
    - rpack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Penlect/rectangle-packer
  summary: Pack a set of rectangles into a bounding box with minimum area
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - BastianZim
