{% set name = "rectangle-packer" %}
{% set version = "2.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rectangle-packer-{{ version }}.tar.gz
  sha256: 34e450029255f726c4a8e6e939a18cad5879f0d9fe588c1878fe85c872dcbe41

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3                              # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cython <3
    - pip
    - python
    - setuptools >=18.0
  run:
    - python

test:
  imports:
    - rpack
  commands:
    - pip check
    - pytest test
  requires:
    - pip
    - pytest
  source_files:
    - test

about:
  home: https://github.com/Penlect/rectangle-packer
  summary: Pack a set of rectangles into a bounding box with minimum area
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - BastianZim
