{% set name = "rectangle-packer" %}
{% set version = "2.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 11e03488618f06c849872a881f72d57174ee4b19a31c0f5c0a1beccf43da87e8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3                              # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython <3
    - pip
    - python
    - setuptools >=18.0
  run:
    - python

test:
  imports:
    - rpack
  commands:
    - pip check
    - pytest test
  requires:
    - pip
    - pytest
  source_files:
    - test

about:
  home: https://github.com/Penlect/rectangle-packer
  summary: Pack a set of rectangles into a bounding box with minimum area
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - BastianZim
